#!/bin/sh

out="$1"
shift

in="`basename "$0"`"
mkdir -p "$out/.idx" "$out/.vscode"
cp "$in/dev.nix" "$out/.idx"
cp "$in/settings.json" "$out/.vscode"

case "$1" in
*\**)
	# Wildcard did not expand. Nothing to extract.
	exit
	;;
esac

for zip in "$@"
do
	dir="$out/`basename -s.zip "$zip"`"
	mkdir "$dir"
	unzip -d "$dir" "$zip"
done
