#!/bin/sh

out="$3"
mkdir -p "$out/.idx" "$out/.vscode"
cp "$1" "$out/.idx/dev.nix"
cp "$2" "$out/.vscode/settings.json"
shift 3

case "$1" in
*\**)
	# Wildcard did not expand. Nothing to extract.
	exit
	;;
esac

for zip in "$@"
do
	dir="$out/`basename -s.zip "$zip"`"
	mkdir "$dir"
	unzip -d "$dir" "$zip"
done
